AWSTemplateFormatVersion: '2010-09-09'
Description: ECR repositories

Parameters:
  Project:
    Type: String
    Default: ecs

Resources:
  JavaApp:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Join ["/", [!Ref Project, "java-app"]]
      RepositoryPolicyText:
        Version: 2008-10-17
        Statement:
          - Sid: AllowPushPull
            Effect: Allow
            Principal:
              AWS: "*"
            Action:
              - ecr:GetDownloadUrlForLayer
              - ecr:BatchGetImage
              - ecr:BatchCheckLayerAvailability
              - ecr:PutImage
              - ecr:InitiateLayerUpload
              - ecr:UploadLayerPart
              - ecr:CompleteLayerUpload
      Tags:
        - Key: Project
          Value: !Ref Project
