AWSTemplateFormatVersion: '2010-09-09'
Description: IAM policy to be attached in ec2 instance role to allow ecs agent to talk to ecs.

Parameters:
  Project:
    Type: String
    Default: ecs
  RoleName:
    Type: String
    Default: ecs-Ecs-Ec2-Role

Resources:
  EcsEc2IamRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref RoleName
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - ec2:DescribeTags
                  - ecs:CreateCluster
                  - ecs:DeregisterContainerInstance
                  - ecs:DiscoverPollEndpoint
                  - ecs:Poll
                  - ecs:RegisterContainerInstance
                  - ecs:StartTelemetrySession
                  - ecs:UpdateContainerInstancesState
                  - ecs:Submit*
                  - ecr:GetAuthorizationToken
                  - ecr:BatchCheckLayerAvailability
                  - ecr:GetDownloadUrlForLayer
                  - ecr:BatchGetImage
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"
      Tags:
        - Key: Project
          Value: !Ref Project

Outputs:
  EcsEc2IamRole:
    Description: The IAM role for ecs ec2 instance.
    Value: !Ref RoleName
    Export:
      Name: !Sub ${Project}:EcsEc2IamRole
