AWSTemplateFormatVersion: '2010-09-09'
Description: IAM Role that allows the jenkins job to create infrustracture via cloudformation.

Parameters:
  Project:
    Type: String
    Default: ecs
    Description: Project name

Resources:
  RootRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Join ["-", [!Ref Project, "Jenkins-Job-Role"]]
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
            Action: sts:AssumeRole

      Path: /
      Policies:
        - PolicyName: all-resources
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - cloudformation:ListExports
                  - ec2:CreateVpc
                  - ec2:DescribeVpcs
                  - ec2:ModifyVpcAttribute
                  - ec2:CreateTags
                  - ec2:DescribeAvailabilityZones
                  - ec2:DescribeAccountAttributes
                  - ec2:DescribeSubnets
                  - ec2:CreateSubnet
                  - ec2:ModifySubnetAttribute
                  - ec2:DeleteSubnet
                  - ec2:CreateRouteTable
                  - ec2:CreateInternetGateway

                  - ec2:DeleteInternetGateway
                  - ec2:DeleteRouteTable
                  - ec2:DescribeRouteTables
                  - ec2:DescribeInternetGateways
                  - ec2:DisassociateRouteTable
                  - ec2:DetachInternetGateway
                  - ec2:DeleteSecurityGroup
                  - ecs:DeleteCluster
                  - autoscaling:DeleteLaunchConfiguration
                  - autoscaling:DeleteAutoScalingGroup
                  - iam:RemoveRoleFromInstanceProfile
                  - iam:DeleteInstanceProfile

                  - ec2:AssociateRouteTable
                  - ec2:AttachInternetGateway
                  - ec2:CreateRoute
#                   ecs ec2
                  - ssm:GetParameters
                  - ec2:DescribeImages
                  - ec2:CreateSecurityGroup
                  - ec2:DescribeSecurityGroups
                  - ecs:DescribeClusters
                  - ecs:CreateCluster
                  - autoscaling:CreateLaunchConfiguration
                  - autoscaling:CreateAutoScalingGroup
                  - autoscaling:UpdateAutoScalingGroup
                  - autoscaling:UpdateAutoScalingGroup # per resource
                  - autoscaling:DescribeAutoScalingGroups
                  - autoscaling:DescribeLaunchConfigurations
                  - autoscaling:DescribeScalingActivities
                  - autoscaling:DescribeAutoScalingInstances
                  - ec2:DescribeInstances
                  - ec2:DescribeKeyPairs
                  - iam:CreateInstanceProfile
                  - iam:AddRoleToInstanceProfile
                Resource: '*'
        - PolicyName: iam-pass-role
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - iam:PassRole
                Resource: !Sub
                  - 'arn:aws:iam::${AWS::AccountId}:role/${Project}-*'
                  - { Project: !Ref Project }
        - PolicyName: cfn-erc-permissions
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - ecr:DescribeRepositories
                  - ecr:CreateRepository
                  - ecr:SetRepositoryPolicy
                  - ecr:DeleteRepository # to be deleted

                  # IAM ECS EXECUTION ROLE
                  - iam:GetRole
                Resource:
                  - !Sub
                    - 'arn:aws:ecr:${AWS::Region}:${AWS::AccountId}:repository/${Project}/*'
                    - { Project: !Ref Project }
        - PolicyName: cfn-resource-specific
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - cloudformation:DescribeStacks
                  - cloudformation:CreateStack
                  - cloudformation:UpdateStack
                Resource:
                  - !Sub 'arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/ecs-vpc/*'
                  - !Sub 'arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/ecs-ec2/*'
                  - !Sub 'arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/ecs-repositories/*'
Outputs:
  CfnRoleArn:
    Description: The CFN arn role.
    Value: !GetAtt  ["RootRole", "Arn"]
    Export:
      Name: !Sub ${Project}:RoleArn
